"""Initial 4 core tables

Revision ID: bdc05495d650
Revises: 
Create Date: 2026-05-16 23:30:33.166950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc05495d650'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investors_email'), 'investors', ['email'], unique=True)
    op.create_index(op.f('ix_investors_id'), 'investors', ['id'], unique=False)
    op.create_table('fund_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_fund_flows_id'), 'fund_flows', ['id'], unique=False)
    op.create_index(op.f('ix_fund_flows_investor_id'), 'fund_flows', ['investor_id'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=50), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('swap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_transactions_id'), 'investment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_investor_id'), 'investment_transactions', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_ticket'), 'investment_transactions', ['ticket'], unique=True)
    op.create_index(op.f('ix_investment_transactions_trade_time'), 'investment_transactions', ['trade_time'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('holding_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shareholding_pct', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_holdings_holding_date'), 'portfolio_holdings', ['holding_date'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_id'), 'portfolio_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_investor_id'), 'portfolio_holdings', ['investor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_holdings_investor_id'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_id'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_holding_date'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_investment_transactions_trade_time'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_ticket'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_investor_id'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index(op.f('ix_fund_flows_investor_id'), table_name='fund_flows')
    op.drop_index(op.f('ix_fund_flows_id'), table_name='fund_flows')
    op.drop_table('fund_flows')
    op.drop_index(op.f('ix_investors_id'), table_name='investors')
    op.drop_index(op.f('ix_investors_email'), table_name='investors')
    op.drop_table('investors')
    # ### end Alembic commands ###
